# Generated by Django 3.0.3 on 2020-05-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='NA', max_length=100)),
                ('email', models.EmailField(default='NA', max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('place', models.CharField(default='NA', max_length=200)),
                ('addr', models.TextField(default='NA')),
                ('ban', models.BooleanField(default=False)),
                ('passwd', models.CharField(default='NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=60)),
                ('smell', models.CharField(max_length=150)),
                ('ph', models.FloatField()),
                ('tds', models.FloatField()),
                ('iron', models.FloatField()),
                ('hardness', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Users')),
            ],
        ),
    ]
