# Generated by Django 3.0.3 on 2020-05-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
