# Generated by Django 3.0.3 on 2020-05-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200531_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Pent_User',
        ),
    ]
