# Generated by Django 3.0.3 on 2020-05-31 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200531_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='test',
            name='colour',
            field=models.CharField(default='NA', max_length=60),
        ),
        migrations.AlterField(
            model_name='test',
            name='hardness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='iron',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='ph',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='smell',
            field=models.CharField(default='NA', max_length=150),
        ),
        migrations.AlterField(
            model_name='test',
            name='tds',
            field=models.FloatField(default=0),
        ),
    ]
