# Generated by Django 3.0.3 on 2020-05-31 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200531_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='added_date',
            new_name='addeddate',
        ),
    ]
