# Generated by Django 3.0.3 on 2020-06-01 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_pent_user_latesttestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pent_user',
            name='latesttestdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
