# Generated by Django 3.0.3 on 2020-06-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_test_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='pent_user',
            name='securitycode',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
