# Generated by Django 3.0.3 on 2020-06-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_pent_user_securitycode'),
    ]

    operations = [
    ]
