# Generated by Django 3.0.3 on 2020-06-14 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200611_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='completiondate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
