# Generated by Django 3.0.3 on 2020-05-30 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200530_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='passwd',
            field=models.CharField(default=datetime.datetime(2020, 5, 30, 12, 8, 53, 754569), max_length=30),
            preserve_default=False,
        ),
    ]
