# Generated by Django 3.0.3 on 2020-05-31 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200530_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager_acc',
            name='firstname',
            field=models.CharField(default=datetime.datetime(2020, 5, 31, 12, 0, 25, 641560), max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager_acc',
            name='lastname',
            field=models.CharField(default=datetime.datetime(2020, 5, 31, 12, 0, 57, 597911), max_length=100),
            preserve_default=False,
        ),
    ]
