# Generated by Django 3.0.3 on 2020-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20200531_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
            ],
        ),
    ]
